version: "3"

services:

  nitter:
    image: zedeus/nitter:latest
    container_name: nitter
    restart: unless-stopped
    volumes:
      - ./nitter.conf:/src/nitter.conf:Z
    networks:
      - nitter
      - redis
    depends_on:
      - redis
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:8080/Jack/status/20 || exit 1
      interval: 15s
      timeout: 5s
      retries: 2
    user: "998:998"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis:/data
    networks:
      - redis
    healthcheck:
      test: redis-cli ping
      interval: 15s
      timeout: 5s
      retries: 2
    user: "999:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - URL=arcticfoxes.net
      - SUBDOMAINS=nitter
      - VALIDATION=http
      - EMAIL=contact@tommytran.io
      - ONLY_SUBDOMAINS=true
    volumes:
      - ./swag:/config:Z
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 443:443
      - 80:80
    networks:
      - nitter
    security_opt:
      - no-new-privileges:true

networks:
  nitter:
  redis:

volumes:
  redis:
